"""
transaction_chart.py
====================
Renders the "Transactions Over Time" line chart using matplotlib.
"""

import streamlit as st
import matplotlib.pyplot as plt
import numpy as np

from data.data_store import DataStore


class TransactionChart:
    """
    Renders an area+line chart showing transaction volume over time.
    Time-series data is generated by DataStore.generate_timeseries().
    """

    # Chart styling constants
    LINE_COLOR      = "#1565c0"
    FILL_COLOR      = "#1565c0"
    FILL_ALPHA      = 0.10
    TICK_COLOR      = "#9ca3af"
    GRID_COLOR      = "#f3f4f6"
    SPINE_COLOR     = "#e5e7eb"
    BG_COLOR        = "#ffffff"
    FIG_SIZE        = (5, 2.6)
    TICK_FONT_SIZE  = 7

    @classmethod
    def _style_axes(cls, ax):
        """Apply consistent light-theme styling to the axes."""
        ax.tick_params(axis="y", colors=cls.TICK_COLOR, labelsize=cls.TICK_FONT_SIZE)
        for spine in ax.spines.values():
            spine.set_color(cls.SPINE_COLOR)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.yaxis.grid(True, color=cls.GRID_COLOR, linewidth=0.8)
        ax.set_axisbelow(True)

    @classmethod
    def render(cls):
        """Draw the section header and the matplotlib line chart."""
        st.markdown(
            '<div class="section-header">📈 Transactions Over Time</div>',
            unsafe_allow_html=True,
        )

        hours, vals = DataStore.generate_timeseries()
        x = np.arange(len(hours))

        fig, ax = plt.subplots(figsize=cls.FIG_SIZE)
        fig.patch.set_facecolor(cls.BG_COLOR)
        ax.set_facecolor(cls.BG_COLOR)

        # Line + markers
        ax.plot(
            x, vals,
            color=cls.LINE_COLOR, linewidth=2.5,
            marker="o", markersize=5,
            markerfacecolor=cls.LINE_COLOR,
            markeredgecolor="#ffffff",
            markeredgewidth=1.5,
        )

        # Fill under line
        ax.fill_between(x, vals, min(vals) - 5, alpha=cls.FILL_ALPHA, color=cls.FILL_COLOR)

        # X-axis labels
        ax.set_xticks(x)
        ax.set_xticklabels(hours, color=cls.TICK_COLOR, fontsize=cls.TICK_FONT_SIZE)

        cls._style_axes(ax)

        plt.tight_layout(pad=0.5)
        st.pyplot(fig, use_container_width=True)
        plt.close(fig)
        st.markdown("")
